# Site settings
title: wyattlam.com
#email: your-email@domain.com
description: "iOS Engineer. Photographer. Coffee Drinker."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wyattlam.com" # the base hostname & protocol for your site
permalink: /posts/:title

# Resource URLs
images: "/resources/"

# Usernames
twitter_username: Wyatt_Lam
github_username:  wyattlam1
flickr_username: wyattlam
linkedin_username: wyattlam
instagram_username: wyattlam

# Site urls
about_url: "/about/"
posts_url: "/posts/"
photo_stories_url: "/photo-stories/"

# Pagination
paginate: 10
paginate_path: "/posts/:num/"

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]

sass:
  style: compressed
